Auto hide sidebar option
getferdi/ferdi pull request #1043
Opened 2020-10-26 16:10 UTC by TGlide

### Description
Add a button to toggle an option to auto hide the sidebar when the cursor is not hovering it

### Motivation and Context
Issue #1026 

### Screenshots
![image](https://user-images.githubusercontent.com/26071571/97197042-f0a26680-178b-11eb-8e76-f3a933ef10a2.png)
![image](https://user-images.githubusercontent.com/26071571/97197187-19c2f700-178c-11eb-9268-805a8b58cc2f.png)

### Checklist:

- [X] My pull request is properly named
- [X] The changes respect the code style of the project (`$ npm run lint`)
- [X] I tested/previewed my changes locally

2020-10-26 22:47 UTC, kris7t requested changes

2020-10-26 22:47 UTC, kris7t commented on src/components/layout/Sidebar.js
> +    const todosToggleMessage = todosStore.isTodosPanelVisible
Is it a good idea to reformat the code in this file like this? I guess our automatic formatting hooks cause this, but it might be difficult to re-synchronize with the Franz upstream later.

2020-10-26 22:47 UTC, kris7t commented on src/styles/layout.scss
> +html {
Note on code reformatting also applies to this file.

2020-10-26 22:47 UTC, kris7t commented on src/components/layout/Sidebar.js
> +              : 'Auto hide sidebar'
These strings should be localized.

2020-10-27 12:51 UTC, kytwb commented on src/components/layout/Sidebar.js
> +    const todosToggleMessage = todosStore.isTodosPanelVisible
I agree, the fewer changes the better, so superfluous reformatting should be avoided.

2020-12-31 12:56 UTC, closed without merging