Build Apple arm64 architecture
getferdi/ferdi pull request #1277
Opened 2021-04-14 01:48 UTC by arioki1

### Description

### Motivation and Context

### Checklist:

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`$ npm run lint`)
- [ ] I tested/previewed my changes locally

2021-04-19 02:36 UTC, vraravam commented
I'm willing to test this if i can get a packaged build (dmg or app) that can run in non-dev mode.

2021-04-19 12:06 UTC, mccoy88f commented
Also waiting for a test build i have to m1 mac (mac mini and macbook air)

2021-04-20 02:04 UTC, arioki1 commented
@vraravam @mccoy88f i've created a build releasde for m1, can you try it https://github.com/arioki1/ferdi/releases/tag/5.6.0-nightly.18-m1

2021-04-20 02:23 UTC, vraravam commented
@arioki1 : Thanks for doing this, but would you mind rebasing from the latest of the `develop` branch of the
parent? I see that your fork is 107 commits behind it - while testing, it
would be good to get the latest and test, wouldn't it?

Also, I'm getting an error when I try with your ARM-based app. (Have attached it to the other issue thread).

2021-04-20 02:32 UTC, vraravam commented
Update on the above: I tried it with a brand new Ferdi profile - and still the same issue persists.

2021-04-20 02:37 UTC, kdlancer commented
I'm getting an error on launch with your latest build release on m1. Please see attached.
![Screenshot 2021-04-19 at 19 31 26](https://user-images.githubusercontent.com/75702713/115329080-9a185280-a146-11eb-9a66-7aaf742dc9dc.jpg)

2021-04-20 03:30 UTC, vraravam commented
If you need to test synchronously, I'm willing to get on a video conference and test it out. btw, I have your latest code in the `native_m1` branch - and still unable to run the npm commands. Any help that you can provide, would unblock me in contributing as well.

2021-04-20 06:55 UTC, mccoy88f commented
Hi same problem with test build.
When i launch i cannot click on OK so i need to force close.
I remove all preference files and trying restart i can click on OK but i cannot do nothing and i can close it normally.
<img width="278" alt="Schermata 2021-04-20 alle 08 50 22" src="https://user-images.githubusercontent.com/50622699/115351030-18f8a400-a1b6-11eb-9e54-3206943b684e.png">

2021-04-20 08:42 UTC, arioki1 commented
I've created a new build, try testing again https://github.com/arioki1/ferdi/releases/tag/5.6.0-nightly.18-m1-2

2021-04-20 08:54 UTC, kdlancer commented
Crash on start, unfortunately. The window starts, flashes, and exits. Here are the system logs:

`Apr 20 01:45:23 Kojis-MacBook-Air com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.kytwb.ferdi.24843606.24843876(501)> [10900]
Apr 20 01:45:23 Kojis-MacBook-Air Ferdi Helper (GPU)[32336]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:23 Kojis-MacBook-Air VTDecoderXPCService[32337]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
Apr 20 01:45:26 Kojis-MacBook-Air com.apple.xpc.launchd[1] (application.com.kytwb.ferdi.24843606.24843876[32334]): Service exited with abnormal code: 1
`

2021-04-20 08:55 UTC, mccoy88f commented
Now the 2nd version boot and works... but Telegram (and telegram react don't load) and google meet say (when try login) browser unsecure.

2021-04-20 09:11 UTC, vraravam commented
@arioki1 - this 2nd version works ! Only request - could you please rebase from the parent fork? I would really like to test the latest changes that have been incorporated.

2021-04-20 09:22 UTC, arioki1 commented
@tokopedia I've experienced it, you need to delete all ferdi data first https://www.howtogeek.com/273722/how-to-reset-any-mac-app-to-its-default-settings/#:~:text=Find%20the%20program%20you%20want,but%20delete%20all%20its%20settings.

2021-04-20 09:32 UTC, arioki1 commented
@vraravam I've made an update on the native_m1 branch

2021-04-20 10:50 UTC, vraravam commented
This is working great! Thanks @arioki1 

I can also notice a marked performance boost on the M1!

2021-04-20 10:51 UTC, vraravam commented
@arioki1 - did you want to squash your commits into a smaller number - logically atomic? (just a suggestion)

2021-04-20 11:01 UTC, arioki1 commented
@vraravam sorry I do not understand about your advice, or you can contribute directly at https://github.com/arioki1/ferdi/tree/native_m1

2021-04-20 11:02 UTC, arioki1 commented
@vraravam Did you experience this, I also experienced and I don't know what went wrong?
> Now the 2nd version boot and works... but Telegram (and telegram react don't load) and google meet say (when try login) browser unsecure.

2021-04-20 11:09 UTC, vraravam commented
np @arioki1 - if you notice the number of commits in this PR - that is 21 commits which have some amount of trial-and-error. I was only referring to those being squashed. not a big deal. Thanks for the work of getting this done though - really appreciate it!

2021-04-20 11:11 UTC, vraravam commented
> @vraravam Did you experience this, I also experienced and I don't know what went wrong?
> 
> > Now the 2nd version boot and works... but Telegram (and telegram react don't load) and google meet say (when try login) browser unsecure.

i did experience it once - but, when restarting Ferdi, after that it worked great. I have quit and restarted Ferdi a few times now. Now, I'm going to run it for a couple of hours without stopping - to check if there are stale zombie workers that get spawned, etc - will report back in a couple of hours

2021-04-20 11:16 UTC, vraravam commented
I have only 1 site that is not working: Telegram (which was setup as a custom site - since both the recipes don't work). And the in-built service recipes continue to not work. But, that is a different issue i suppose.

2021-04-20 11:44 UTC, vraravam commented
I was reviewing the changes @arioki1 , and these are my comments
1) Wow - we jumped from electron 10.2 to 11.4! Awesome!
2) I see that we have commented out `processManager` - would that affect any functionality?

2021-04-20 11:54 UTC, arioki1 commented
@vraravam I have removed processManager as in this discussion https://github.com/getferdi/ferdi/issues/875#issuecomment-819164858 i haven't tested whether this processManager removal affects functionality or not

2021-04-20 11:58 UTC, arioki1 commented
previously I had been looking for whether https://github.com/meetfranz/franz using processManager or not and it turned out not to be. therefore I decided to remove it because it caused an error when `npx lerna bootstrap`

2021-04-20 12:25 UTC, vraravam commented
Looking at the `git blame src/electron/ipc-api/processManager.js` for this file, it looks like this file and the dependency on the `processManager` package was introduced by @vantezzen in this commit: ef6fbfbd0

2021-04-20 23:14 UTC, vraravam commented
@arioki1 - you might want to remove the "DRAFT" from the title of the PR - I think it might be held back due to that?

2021-04-21 01:10 UTC, arioki1 commented
@vraravam it seems that in order for us to use processManager we have to update the dependency, because the depedence is no longer updated

2021-04-26 11:57 UTC, vraravam commented
@arioki1 - could you please rebase from the parent branch (`develop`) and resolve the conflicts? Based on other PRs, we are now ahead of your version of `electron`.
My suggestion: could you please check if you can make changes inside of this PR for the `appveyor.yml` - so that the CI proscess can also generate both x86 and arm -targeted artifacts?

2021-04-29 07:13 UTC, kytwb commented
@all-contributors please add @arioki1 for platform

2021-04-29 07:13 UTC, kytwb commented
@all-contributors please add @vraravam for mentoring

2021-04-29 07:29 UTC, vraravam commented
@arioki1 - could you please rebase from `develop`? 

From my perusal of the code, most of your changes are already in other PRs and the only one outstanding is #1308 . Other than that, what will be left is your changes to the `electron-builder.yml` file. Please ack/confirm. I would like to get these merged so that we can then focus on the ARM builds in appveyor

cc @kris7t @kytwb

2021-04-29 11:00 UTC, kytwb commented
@arioki1 it seems merging https://github.com/getferdi/ferdi/pull/1308 created a new conflict on the lockfile, please advise.

2021-04-29 11:11 UTC, vraravam commented on package.json
> +    "macos-notification-state": "1.3.5",
This not really required since this dependency is brought in as a transitive dep.

2021-04-29 11:12 UTC, vraravam commented on packages/theme/test/index.test.js
> +/*
I am able to run all tests - we should not comment them out.

2021-04-29 11:13 UTC, kytwb commented
@all-contributors please add @vraravam for review

2021-04-29 11:22 UTC, vraravam requested changes
Please see above comments

2021-04-29 11:31 UTC, kytwb commented on package.json
> +    "macos-notification-state": "1.3.5",
```suggestion
```

2021-04-29 11:32 UTC, kytwb commented on packages/theme/test/index.test.js
> +*/
```suggestion
```

2021-04-29 11:32 UTC, kytwb commented on packages/theme/test/index.test.js
> +/*
```suggestion
```

2021-04-29 11:33 UTC, vraravam commented
This is now verified on a mac ARM machine:
<img width="279" alt="Screenshot 2021-04-29 at 5 01 50 PM" src="https://user-images.githubusercontent.com/69629/116544387-ae114080-a90c-11eb-9d5c-2ee7b5f10e33.png">

2021-04-29 11:34 UTC, vraravam commented
@arioki1 - since the only final change is limited to 1 file- can you please remove the changes in `package-lock.json` please?

2021-04-29 13:08 UTC, vraravam commented
@kytwb - since I see that you have made a commit for the review comments - can you please fix the outstanding one about the `package-lock.json` - and merge this please? Need ARM support and nightlies out for others to test.

2021-04-29 13:59 UTC, merged