Upgrade node, npm and specify/lock node-gyp versions.
getferdi/ferdi pull request #1399
Opened 2021-05-12 16:17 UTC by vraravam

### Description
Going to the latest version and locking for trialing building on ARM laptop.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

2021-05-12 17:01 UTC, kris7t commented
Do we really need exact versions? E.g., Arch only has nodejs 14.16.0 (even in `[testing]`). The package [was already flagged out of date](https://archlinux.org/packages/community/x86_64/nodejs-lts-fermium/), but will probably require a couple of days before getting updated. Nevertheless (safe for the version incompatibility error introduced by this PR), I have no problems with building Ferdi.

2021-05-12 23:51 UTC, vraravam commented
> Do we really need exact versions? E.g., Arch only has nodejs 14.16.0 (even in `[testing]`). The package [was already flagged out of date](https://archlinux.org/packages/community/x86_64/nodejs-lts-fermium/), but will probably require a couple of days before getting updated. Nevertheless (safe for the version incompatibility error introduced by this PR), I have no problems with building Ferdi.

In which case, do you want to hold off for a few days and then merge this PR? If so, I will wait for your explicit approval before merging this.

2021-05-13 09:39 UTC, kris7t commented
Is there something specific in 14.17.0 that we need to arm macs? In that case, I'm ok with holding this off for a bit and then merging. But looking through distro packages e.g., at https://pkgs.org/search/?q=nodejs it seems many distributions only carry 14.16, and those are likely on slower update cadences than Arch. So if we merge this, we (temporarily) exclude a bunch of distros from building Ferdi. (I only looked at distros on this list that package nodejs 14. Those on 12 are likely to use `nvm`, anyway, but it's nice to be able to rely on the native package if one is available with the correct major version.)

If 14.16 is enough, I'd be more comfortable with something like `^14.16.0` (and caret dependencies for `node-gyp` and `npm`, too, as most distros wouldn't update at _exactly_ the same time).

2021-05-13 09:45 UTC, vraravam commented
Yes - Im ok with changing to the `^` based notations for dev/build-time-system-deps. Let me make that commit.

2021-05-13 10:01 UTC, kris7t approved these changes
Builds fine for me now

2021-05-13 10:04 UTC, kris7t requested changes

2021-05-13 10:04 UTC, kris7t commented on appveyor.yml
> +  nodejs_version: "^14.16"
Apparently, AppVeyor fails on this? I guess we need exact versions in `appveyor.yml` (and maybe `.travis.yml`, but that build hasn't finished yet).

2021-05-13 10:07 UTC, vraravam commented on appveyor.yml
> +  nodejs_version: "^14.16"
yes - reverted to the same -tx

2021-05-13 10:09 UTC, vraravam commented
In the end, the PR got changed to only be used to enforce the `<major>.<minor>` versions for the system-level dependencies. Upgrades have been rolled back since linux contributors might not be in a position to upgrade.

2021-05-13 10:21 UTC, merged