Adding DuckDuckGo as an alternative search engine. [WIP]
getferdi/ferdi pull request #1414
Opened 2021-05-14 17:28 UTC by vraravam

TODO: Need to read from the settings store, and use the choice to build
the contextMenu in src/webview/contextMenuBuilder.js

### Description
Provide a choice to the user with a different search engine (Duck Duck Go in this case).

### Motivation and Context
Allow the user a choice of search engines.

### Screenshots

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

2021-05-14 23:51 UTC, kris7t commented
Looks like the context menu is created within the service webview, so we'll need to use the mechanism that sends the settings into the webview from the app. Luckily, this already exists for supporting spell checking:

https://github.com/getferdi/ferdi/blob/480500d50d97f9a520495b782cd0b1e52153cdfc/src/webview/recipe.js#L151-L155

So most likely adding another constructor argument to `contextMenu` and returning the appropriate value from `this.settings.app` in the passed lambda should work fine.

2021-05-15 03:06 UTC, vraravam commented
Thanks for the pointer @kris7t - but, its still not working.
<img width="793" alt="Screen Shot 2021-05-15 at 8 35 17 AM" src="https://user-images.githubusercontent.com/69629/118346382-94046e80-b558-11eb-8cda-7a40e338a4fd.png">

I have committed the new code as per your suggestions in a separate commit - please help.

2021-05-15 07:28 UTC, vraravam commented
This is now working - thanks @kris7t for the pointer. Please review asap.

2021-05-15 12:00 UTC, kris7t requested changes

2021-05-15 12:00 UTC, kris7t commented on src/webview/contextMenuBuilder.js
> +        const url = `${SEARCH_ENGINE_URLS[menuInfo.searchEngine]}${encodeURIComponent(menuInfo.selectionText)}`;
Replacing a placeholder `%q` here would feel cleaner than just appending the query, if we eventually want to support custom search engines.

2021-05-15 12:13 UTC, vraravam commented on src/config.js
> +  searchEngine: SEARCH_ENGINE_DDG,
Yes, the default has been changed to DDG - in light of privacy. Do you want to keep the default as google?

It serializes the key that is passed around in the code `SEARCH_ENGINE_GOOGLE` or `SEARCH_ENGINE_GOOGLE`. Imo, its better to pass a enum/variable rather than a string literal. But, if you want me to change it to `google` or `duckDuckGo` - I can do it. What's your preference?

2021-05-15 12:28 UTC, kris7t commented on src/config.js
> +  searchEngine: SEARCH_ENGINE_DDG,
No, I mean I'd prefer DuckDuckGo as the default, but it nevertheless default to Google for me.

The problem is that we should be passing the constants like `SEARCH_ENGINE_DDG`  (with value `'duckDuckGo'`) in the code, but you inadvertently made `SEARCH_ENGINE_NAMES` keyed with the _string_ `'SEARCH_ENGINE_DDG'`, because js array literals are silly like that (see below). Thus, it tries to find the entry with key `SEARCH_ENGINE_DDG`  (aka the _string_ `'duckDuckGo'`, but there isn't any, so it default to the first entry, which happens to be the one with the key _string_ `'SEARCH_ENGINE_GOOGLE'`. By using the appropriate keys in the two config arrays (with the `[SEARCH_ENGINE_DDG]: ` notation, we restore the intended behavior with DuckDuckGo as the default.

2021-05-15 13:04 UTC, kris7t approved these changes

2021-05-15 13:04 UTC, merged