Expose Chrome version to todos webview (fix #1211)
getferdi/ferdi pull request #1478
Opened 2021-06-01 16:37 UTC by kris7t

### Description
The TickTick todo service fails to load if the Chrome version number does not appear in the User-Agent string. However, login to Google Tasks is prevented by the same.

We adopt the "chromeless" User-Agent logic from the service webview, which selectively exposes the Chrome version everywhere except the Google login screen. The common logic was moved into the userAgent-helpers module.

### Motivation and Context
Fixes #1211 

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

2021-06-01 23:48 UTC, vraravam requested changes

2021-06-01 23:48 UTC, vraravam commented on src/features/todos/store.js
> +    const handleUserAgent = (url, forwardingHack = false) => {
@kris7t - isn't this `handleUserAgent` function duplicated between here and the `Service` model? If so, can the duplication be removed?

2021-06-01 23:56 UTC, kris7t commented on src/features/todos/store.js
> +    const handleUserAgent = (url, forwardingHack = false) => {
It is not an exact duplicate, because in the `Service` model, the "chromeful" user agent is `this.userAgent`, i.e., whatever the recipe specifies for the service. Nevertheless, I was thinking about how to extract the common logic into a new model (holding the "chromeful" user agent and the corresponding flag as state) that is used by composition in both `Service` and here. I can try to do that, but I don't know off the top of my had how to do that with mobx models.

2021-06-02 00:07 UTC, vraravam commented on src/features/todos/store.js
> +    const handleUserAgent = (url, forwardingHack = false) => {
ok - if it is much more convoluted, lets put a `TODO` in both places and move onto approving this PR. We can solve the `TODO` at a later date.

2021-06-03 15:39 UTC, vraravam approved these changes
I haven't run this on my local - but, it seems correct. Please merge based on your confidence and local testing.

2021-06-03 17:01 UTC, merged

2021-06-14 08:20 UTC, Rixxx-git commented
Is this fix already part of the latest beta version? 🙂  I just installed the latest beta but ticktick is still stuck on loading. I don't know why but it worked the first time I set up the todo service. On restart it gets stuck on loading.

2021-06-14 09:06 UTC, kris7t commented
@Rixxx-git No, but it should arrive in a nightly soon.

2021-06-14 09:35 UTC, Rixxx-git commented
Alright. Thank you for your help!

2021-07-18 16:04 UTC, Rixxx-git commented
@kris7t Will this issue be fixed in the upcoming version 5.6.0?

2021-07-18 17:35 UTC, kris7t commented
This should already be in the latest beta, I think.

2021-07-18 17:40 UTC, vraravam commented
I just released v5.6.0 - this should be in there!
The website and homebrew formulae are still in the process of being approved/merged. Please see progress in #1017