Fix active Todos service behaviour
getferdi/ferdi pull request #1481
Opened 2021-06-02 22:20 UTC by kytwb

### Description

Franz 5.6.0 came with a new behaviour related to Franz Todos. If a user adds Franz Todos as a service and uses Franz Todos simultaneously, the TodosWebView gets expended when the user switches to the Franz Todos service.

### Motivation and Context

For https://github.com/getferdi/ferdi/issues/1017#issuecomment-775014033.  

Ferdi offering multiple alternatives to Franz Todos, this pull request aim at maintaining this behaviour for the supported alternatives.

### Screenshots

<img width="912" alt="Screen Shot 2021-06-03 at 12 12 42 AM" src="https://user-images.githubusercontent.com/412895/120558894-0b128180-c3f8-11eb-9316-85a0033b582b.png">

<img width="912" alt="Screen Shot 2021-06-03 at 12 12 55 AM" src="https://user-images.githubusercontent.com/412895/120558909-11a0f900-c3f8-11eb-912f-e51fb773d3ad.png">

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

2021-06-02 22:36 UTC, vraravam requested changes

2021-06-02 22:36 UTC, vraravam commented on src/config.js
> +export const TODOS_RECIPES_ID = {
Can we rename this variable to show more meaning please?

2021-06-02 22:36 UTC, vraravam commented on src/config.js
> +export const TODOS_RECIPES_ID = {
Also, since this variable and `TODO_APPS` seem to overlap, why not combine them?

2021-06-02 22:36 UTC, vraravam commented on src/models/Service.js
> +    if (this.recipe.id === TODOS_RECIPES_ID[window.ferdi.stores.settings.all.app.predefinedTodoServer]) {
This logic (of looking up from the config struct and comparing to another value) seems repeated. Can it be moved into a method and reused?

2021-06-02 22:36 UTC, vraravam commented on src/stores/ServicesStore.js
> +    return this.allDisplayed.find(service => service.recipe.id === TODOS_RECIPES_ID[this.stores.settings.all.app.predefinedTodoServer] && service.isEnabled) || false;
repetitive logic - can it be moved into a method and reused?

2021-06-02 22:36 UTC, vraravam commented on src/stores/ServicesStore.js
> +    return this.active && this.active.recipe.id === TODOS_RECIPES_ID[this.stores.settings.all.app.predefinedTodoServer];
repetitive logic - can it be moved into a method and reused?

2021-06-02 22:36 UTC, vraravam commented on src/stores/ServicesStore.js
> +    if (this.active.recipe.id === TODOS_RECIPES_ID[this.stores.settings.all.app.predefinedTodoServer] && !this.stores.todos.settings.isFeatureEnabledByUser) {
repetitive logic - can it be moved into a method and reused?

2021-06-02 22:36 UTC, vraravam commented on src/stores/ServicesStore.js
> +    if (service.recipe.id === TODOS_RECIPES_ID[this.stores.settings.all.app.predefinedTodoServer]) {
repetitive logic - can it be moved into a method and reused?

2021-06-02 22:36 UTC, vraravam commented on src/stores/ServicesStore.js
> +    if (service.recipe.id === TODOS_RECIPES_ID[this.stores.settings.all.app.predefinedTodoServer]) {
repetitive logic - can it be moved into a method and reused?

2021-06-02 23:39 UTC, kris7t commented on src/models/Service.js
> +    if (this.recipe.id === TODOS_RECIPES_ID[window.ferdi.stores.settings.all.app.predefinedTodoServer]) {
I'd recommend extracting the todo recipe id to a `@computed` in the `SettingsStore`, for example.

2021-06-03 23:34 UTC, kris7t commented
I took my stab at refactoring this to move the common logic into mobx stores. Feel free to edit or force-push the previous version if something's off.

2021-06-03 23:45 UTC, vraravam requested changes

2021-06-03 23:45 UTC, vraravam commented on src/config.js
> +export const TODO_SERVICE_RECIPE_IDS = {
My preference is to have the lookup key be an internal simple word, and the value be a complex string that is not duplicated (even within the same file). Can these be swapped in this config array - and the other one use the same keys? Similar to how I have done the 2 for search engines?

2021-06-03 23:45 UTC, vraravam commented on src/config.js
> +export const TODO_SERVICE_RECIPE_IDS = {
Maybe also rename the variable to have better appropriate names.

2021-06-03 23:45 UTC, vraravam commented on src/features/todos/store.js
> +function validURL(str) {
I think there's a `isValidExternalUrl` used elsewhere in the codebase - is this duplicated?

2021-06-03 23:45 UTC, vraravam commented on src/features/todos/store.js
> +function validURL(str) {
Also, is it better to move this into a `url_helper.js` as opposed to be in this file?

2021-06-03 23:50 UTC, kris7t commented on src/config.js
> +export const TODO_SERVICE_RECIPE_IDS = {
We probably should keep using the URLs as the keys, because we've already saved the URL into `settings.json`, and changing this would break users' setting. A possible solution is to have a bunch of `const` variables with the URLs, and use them as keys.

It's also a bit subtle, because here we're collecting recipe IDs for todo services, and not all todo services that we have an URL for have an associated recipe (and thus recipe ID).

What idea do you have for a better variable name?

2021-06-03 23:56 UTC, vraravam commented on src/config.js
> +export const TODO_SERVICE_RECIPE_IDS = {
@kris7t - if the SaaS todo service changes it domain name (for eg adds an `api` in front to differentiate the marketing site vs the actual users' area), that would break everything here, right? So, presence in `settings.json` would also be broken in that case?

2021-06-04 00:00 UTC, vraravam commented on src/config.js
> +export const TODO_SERVICE_RECIPE_IDS = {
imo - we can callout that the settings change is an unfortunate, but necessary backward incompatible change, and prompt the user to choose anew.

2021-06-04 00:03 UTC, kris7t commented on src/config.js
> +export const TODO_SERVICE_RECIPE_IDS = {
Yes, we're basically coupled to the URL with the current design. We could refactor this e.g., in a later PR, but that would need some kind of `settings.json` migration infrastructure. Which would probably be a good idea anyways, giving us greater freedom in changing things in the app...

2021-06-04 00:11 UTC, vraravam commented on src/config.js
> +export const TODO_SERVICE_RECIPE_IDS = {
ok - lets go with this as the understanding - and we can ideate on the settings-change-infra outside of this PR - since its a much bigger change.

2021-06-04 00:12 UTC, vraravam commented
Assuming @kytwb is ok with the direction/changes, I'm 👍

2021-06-04 00:17 UTC, kris7t commented
Actually, there's a `_migrate` method on `SettingsStore` which may help with the settings migration.

2021-06-04 01:22 UTC, vraravam commented
so, in which case, we can use that to migrate and not incur tech-debt here?

2021-06-04 09:31 UTC, kris7t commented
I'm looking into it, but so far, it seems we can't because the migrations don't have access to the previous contents of `settings.yaml`.

2021-06-11 14:56 UTC, kris7t approved these changes

2021-06-12 16:42 UTC, kris7t commented
@kytwb @vraravam Can we go ahead and merge this?

2021-06-12 17:05 UTC, vraravam approved these changes

2021-06-12 17:51 UTC, merged