Removed the cyclical dependency  (#1519)
getferdi/ferdi pull request #1539
Opened 2021-06-19 14:45 UTC by markandan

### Description

### Motivation and Context

### Screenshots

### Checklist:

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`$ npm run lint`)
- [ ] I tested/previewed my changes locally

2021-06-19 15:01 UTC, vraravam requested changes

2021-06-19 15:01 UTC, vraravam commented on src/features/todos/store.js
> +  CUSTOM_TODO_SERVICE, TODO_SERVICE_RECIPE_IDS, DEFAULT_TODOS_WIDTH, TODOS_MIN_WIDTH, DEFAULT_TODOS_VISIBLE, DEFAULT_IS_FEATURE_ENABLED_BY_USER,
Did you run the linter? Usually for this many imports from a single module, the linter puts them into a multi-line form.

2021-06-22 01:26 UTC, markandan commented on src/features/delayApp/index.js
> +export const config = configurations;
Export is not needed. Removed the export from index file.

2021-06-22 01:58 UTC, vraravam commented on src/features/delayApp/index.js
> +export const config = configurations;
Since this is now internal to this 1 file, can we not use `configurations` always (in this file) and remove references to `config`? Or is there a reason for keeping them separate?

2021-06-22 01:59 UTC, vraravam commented on src/features/todos/store.js
> +  CUSTOM_TODO_SERVICE, TODO_SERVICE_RECIPE_IDS, DEFAULT_TODOS_WIDTH, TODOS_MIN_WIDTH, DEFAULT_TODOS_VISIBLE, DEFAULT_IS_FEATURE_ENABLED_BY_USER,
no - please don't manually modify - let the linter work as it does. Coz, this how others will build on top of your commit - and also the CI process will anyway flag this as a break.

2021-06-22 02:34 UTC, markandan commented on src/features/todos/store.js
> +  CUSTOM_TODO_SERVICE, TODO_SERVICE_RECIPE_IDS, DEFAULT_TODOS_WIDTH, TODOS_MIN_WIDTH, DEFAULT_TODOS_VISIBLE, DEFAULT_IS_FEATURE_ENABLED_BY_USER,
Even after doing it manually ran EsLint it is not changing anything.. .This should be fine

2021-06-22 02:36 UTC, vraravam requested changes

2021-06-22 02:36 UTC, vraravam commented on src/features/delayApp/index.js
> +const config = configurations;
Can this not be combined into line 4 without the `as` portion?

2021-06-22 05:16 UTC, markandan commented on src/features/delayApp/index.js
> +const config = configurations;
Updated @vraravam

2021-06-22 05:24 UTC, vraravam approved these changes

2021-06-22 05:26 UTC, merged

2021-06-22 05:27 UTC, vraravam commented
@all-contributors please add @markandan for code