Upgrade various dependencies to latest part 2
getferdi/ferdi pull request #1557
Opened 2021-06-24 01:52 UTC by mhatvan

### Description

- upgraded `eslint` deps to latest
- replaced deprecated `node-sass` with `sass`
- got rid of old React lifecycles
- autofixed all new lint issues from updated `eslint-config-airbnb`
- added minimal `settings.json` file for vscode users

### Motivation and Context

References #1495

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [ ] I tested/previewed my changes locally

2021-06-24 02:30 UTC, vraravam requested changes
Please review the comments and fix/respond. Also, might it have been easier to separate the upgrade of `react` from the upgrade of `eslint`? Or were they needed to be upgraded in tandem?

2021-06-24 02:30 UTC, vraravam commented on src/components/auth/Import.js
> +  componentDidMount() {
Isn't this changing the semantics of the lifecycle event that is being overridden? (I'm not a Js/UI dev - so, maybe I'm asking a wrong q here - please forgive me if so)

2021-06-24 02:30 UTC, vraravam commented on src/components/auth/Invite.js
> +  componentDidMount() {
Same comment about changing behavior

2021-06-24 02:30 UTC, vraravam commented on src/components/settings/SettingsLayout.js
> +  componentDidMount() {
Same q about the changing behavior

2021-06-24 02:30 UTC, vraravam commented on src/components/settings/SettingsLayout.js
> +              aria-label="Close Settings"
Need to extract for i18n

2021-06-24 02:30 UTC, vraravam commented on src/components/settings/SettingsLayout.js
> +                aria-label="Close Settings"
Need to extract for i18n

2021-06-24 02:30 UTC, vraravam commented on src/components/ui/InfoBar.js
> +            aria-label="Hide"
Need to extract for i18n

2021-06-24 02:30 UTC, vraravam commented on src/components/ui/Infobox.js
> +            aria-label="Dismiss"
Need to extract for i18n

2021-06-24 02:30 UTC, vraravam commented on src/components/ui/Input.js
> +              aria-label="Password toggle"
Need to extract for i18n

2021-06-24 02:30 UTC, vraravam commented on src/components/ui/Tabs/Tabs.js
> +  componentDidMount() {
Same q about the changing behavior

2021-06-24 02:30 UTC, vraravam commented on src/features/todos/components/TodosWebview.js
> +  componentDidMount() {
Same q about the changing behavior

2021-06-24 02:30 UTC, vraravam commented on src/features/workspaces/containers/EditWorkspaceScreen.js
> +      ({ saving: true, ...workspaceBeingEdited, ...values }),
Doesn't this need to be:
`({ saving: true }, ...workspaceBeingEdited, ...values)`

2021-06-24 02:44 UTC, mhatvan commented
> Please review the comments and fix/respond. Also, might it have been easier to separate the upgrade of `react` from the upgrade of `eslint`? Or were they needed to be upgraded in tandem?

Unforunately it was necessary to fix the react lifecycle issues, because they were reported with error level due to `eslint-config-airbnb` upgrade.

2021-06-24 02:45 UTC, mhatvan commented on src/features/workspaces/containers/EditWorkspaceScreen.js
> +      ({ saving: true, ...workspaceBeingEdited, ...values }),
This is autofixed by eslint, no manual change from my side.
And I can verify that it is correct.

2021-06-24 02:47 UTC, mhatvan commented on src/components/auth/Import.js
> +  componentDidMount() {
You can read more about it here: https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

In general, code can be moved to `constructor()` or into `componentDidMount()` to replicate behavior like before.

2021-06-24 02:48 UTC, vraravam commented on src/components/auth/Import.js
> +  componentDidMount() {
If so, should we move these into `constructor()`?

2021-06-24 02:49 UTC, vraravam commented on src/features/workspaces/containers/EditWorkspaceScreen.js
> +      ({ saving: true, ...workspaceBeingEdited, ...values }),
ok - tx

2021-06-24 03:20 UTC, mhatvan commented on src/components/auth/Import.js
> +  componentDidMount() {
`componentDidMount()` is safer in cases like `document.addEventListener()` and complex code because the component is mounted then for sure. Will leave as is.

2021-06-24 03:35 UTC, vraravam commented on .vscode/settings.json
> +{
Since this file is specific to VS Code as the text editor/IDE - can we move this into something that is agnostic of the editor? ie something that'll work from the cmd-line?

2021-06-24 03:49 UTC, vraravam commented on .vscode/settings.json
> +{
Something like a `.prettierrc` file?

2021-06-24 03:50 UTC, mhatvan commented on .vscode/settings.json
> +{
I fear not because then there would still be errors shown about experimental decorator issues etc in the IDE. This file is there mostly for improved DX for VSCode users.

2021-06-24 03:52 UTC, vraravam commented
I see that you have not checked the 3rd self-verification by running the app locally - can you please confirm that this is done?

2021-06-24 03:53 UTC, vraravam approved these changes

2021-06-24 12:58 UTC, kris7t requested changes
Creating or editing a workspace seems to fail for me. I'll try to debug later, but in the meantime, if you have an idea how to fix it, it would also be great.

2021-06-24 14:19 UTC, mhatvan commented
> Creating or editing a workspace seems to fail for me. I'll try to debug later, but in the meantime, if you have an idea how to fix it, it would also be great.

My bad, `static getDerivedStateFromProps()` seemed to break it.
I was not able to find a proper replacement for `componentWillReceiveProps()`, so I changed it back in the latest commit.
It was out of scope anyways and hopefully the code wil be upgraded to hooks at some points ;)

2021-06-24 14:57 UTC, vraravam commented
Thanks @mhatvan - with [this last commit](https://github.com/getferdi/ferdi/pull/1557#issuecomment-867675869) - I'm able to create + edit workspaces as well.

2021-06-24 17:29 UTC, mhatvan commented
> Thanks @mhatvan - with [this last commit](https://github.com/getferdi/ferdi/pull/1557#issuecomment-867675869) - I'm able to create + edit workspaces as well. When merging the PR - please ensure that you squash all the commits into more meaningful ones (maybe a single one) and then rebase (not merge) into the `develop` branch. Also, please ensure that you run the `npm run lint && npm run reformat-files` commands before committing - since there seem to be some leftover changes when i run these commands on top of your commits.

Indeed, there are leftover file changes from `npm run apply-branding`, these are not staged and included in the commit automatically which is the problem.

I am used to "squash and merge" GitHub merge strategy from other projects, is this fine or do I have to prepare the commits before pushing?

2021-06-24 23:47 UTC, vraravam commented
> Indeed, there are leftover file changes from npm run apply-branding, these are not staged and included in the commit automatically which is the problem.

Yes - please include them in the PR.

> I am used to "squash and merge" GitHub merge strategy from other projects, is this fine or do I have to prepare the commits before pushing?

This is ok - please just ensure that the resulting cumulative commit comment is edited to be streamlined.

2021-06-25 04:02 UTC, mhatvan commented
I included the changed files from apply-branding into the PR. 
I can recommend combining husky with https://github.com/okonet/lint-staged to make sure that file changes from scripts are correctly staged before the actual commit is happening.

I will squash and merge this PR once the approval is in from @kris7t

2021-07-01 04:13 UTC, mhatvan commented
@kris7t Did you manage to have another look over this?
I would like to get this merged and then start another sweep of dependency upgrades ;)

2021-07-02 02:53 UTC, vraravam commented
@mhatvan - do you mind rebasing from the latest `develop` branch ? And after that, giving it another day, if @kris7t is unable to respond (I know he is busy with his day job), maybe you can go ahead and squash-merge this PR. (Worst-case scenario, we can revert that single commit if it causes other problems).

As always, I assume that you have tested these locally?

2021-07-03 00:14 UTC, kris7t approved these changes
Sorry for taking so long to review! Tried this out locally, and it LGTM to me, too.

2021-07-03 01:47 UTC, vraravam commented
@all-contributors - please add @mhatvan for code

2021-07-03 01:49 UTC, merged