chore: run security audit on node modules
getferdi/ferdi pull request #1621
Opened 2021-07-07 08:01 UTC by mhatvan

#### Description of Change

- changed electron target for @babel/preset-env from 4 to 11
- added .prettierrc.js with conforming settings to current code style
- removed unmaintained @adlk/misty to fix CVE
- upgraded gulp-sass to v5 to fix CVE and adapted code to breaking changes
- refreshed package-lock.json of packages/forms and packages/ui
- upgraded normalize-url to fix CVE
- removed unnecessary @types/color-convert
- fix ToggleComponent breaking tsc compilation

#### Motivation and Context
Closes https://github.com/getferdi/ferdi/issues/1496

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint && npm run reformat-files && npm run manage-translations && npm run apply-branding`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

2021-07-07 08:09 UTC, vraravam requested changes

2021-07-07 08:09 UTC, vraravam commented on .babelrc
> +          "electron": 11
@mhatvan - we are on electron 13 - should this be `13` instead of `11`?

2021-07-07 08:09 UTC, vraravam commented on CONTRIBUTING.md
> -Optionally, you can run both commands in one terminal with [misty](https://github.com/adlk/misty) (see [misty.yml](https://github.com/getferdi/ferdi/blob/develop/misty.yml)):
Why are we removing this? Its very useful for contributors like me

2021-07-07 08:09 UTC, vraravam commented on package.json
> -    "@adlk/misty": "^0.2.0",
Has this been removed since it's no longer compatible?

2021-07-07 08:11 UTC, vraravam commented
@mhatvan - rather than removing `misty` - is there a possibility to submit a PR for that ? Since its a dev-dependency, I'm not too sure whether removing it is really necessary in this PR. Lets have a discussion on this before removing this please.

2021-07-07 08:15 UTC, mhatvan commented on .babelrc
> +          "electron": 11
To my understanding, this is how babel decides what the lowest target is that it needs to transpile to, also see: https://babeljs.io/docs/en/babel-preset-env#targets

The oldest still supported Electron version is 11 which can be seen here: https://www.electronjs.org/docs/tutorial/support#currently-supported-versions

2021-07-07 08:18 UTC, mhatvan commented on CONTRIBUTING.md
> -Optionally, you can run both commands in one terminal with [misty](https://github.com/adlk/misty) (see [misty.yml](https://github.com/getferdi/ferdi/blob/develop/misty.yml)):
I removed it to see how much I can get rid of the security vulnerabilities, but I am also fine with re-adding it.
Is there any alternative tool to misty that runs multiple commands in one terminal that you could use?
I know there is https://www.npmjs.com/package/concurrently and https://www.npmjs.com/package/npm-run-all just to name a few.

2021-07-07 08:19 UTC, mhatvan commented on package.json
> -    "@adlk/misty": "^0.2.0",
See reasoning above.

2021-07-07 08:21 UTC, mhatvan commented
> @mhatvan - rather than removing `misty` - is there a possibility to submit a PR for that ? Since its a dev-dependency, I'm not too sure whether removing it is really necessary in this PR. Lets have a discussion on this before removing this please.

Yeah, I wouldn't do such drastic changes like removing it without approval anyways, don't worry.
I think there is so much work to maintain Ferdi already without having to take over ownership for another lib. Ideally we can use another 3rd party lib.

2021-07-07 08:26 UTC, vraravam commented on .babelrc
> +          "electron": 11
`electron-builder` is supporting a "lowest electron version" since its a library/tool that others use; but in our case of Ferdi, we are the final user. Lets continue this conversation in the gitter channel.

2021-07-07 08:26 UTC, vraravam commented on CONTRIBUTING.md
> -Optionally, you can run both commands in one terminal with [misty](https://github.com/adlk/misty) (see [misty.yml](https://github.com/getferdi/ferdi/blob/develop/misty.yml)):
If we have a replacement, thatn I'm fine. Else, please re-add it back it (for now at least)

2021-07-07 23:38 UTC, vraravam requested changes
Can we also NOT upgrade the `recipes` submodule? Unless its directly pertinent to this PR, I would like for that to be handled by the automated CI process.

2021-07-07 23:38 UTC, vraravam commented on .babelrc
> +          "electron": 11
Please change this to `13`

2021-07-07 23:38 UTC, vraravam commented on CONTRIBUTING.md
> -Optionally, you can run both commands in one terminal with [misty](https://github.com/adlk/misty) (see [misty.yml](https://github.com/getferdi/ferdi/blob/develop/misty.yml)):
Not sure why this is still showing up as "changed"

2021-07-08 00:13 UTC, vraravam commented on package.json
> -    "@adlk/misty": "^0.2.0",
As discussed in gitter, please resurrect.

2021-07-08 06:07 UTC, mhatvan commented on CONTRIBUTING.md
> -Optionally, you can run both commands in one terminal with [misty](https://github.com/adlk/misty) (see [misty.yml](https://github.com/getferdi/ferdi/blob/develop/misty.yml)):
It is simply a whitespace change that was missing before.

2021-07-08 06:26 UTC, mhatvan commented
> Can we also _not_ upgrade the `recipes` submodule? Unless its directly pertinent to this PR, I would like for that to be handled by the automated CI process.

I tried to undo it by git resetting to the commit hash that is on the ferdi repo `develop` branch but I don't see any changed files then and probably would need to force push an old version. Can we just get this merged as is?

2021-07-08 06:27 UTC, vraravam commented
> I tried to undo it by git resetting to the commit hash that is on the ferdi repo `develop` branch but I don't see any changed files then and probably would need to force push an old version. Can we just get this merged as is?

ok - this time, lets go ahead - but, please watch out for this in the future.

2021-07-08 06:28 UTC, vraravam approved these changes

2021-07-08 07:21 UTC, merged