Check if default app protocol fix
getferdi/ferdi pull request #1818
Opened 2021-08-20 09:04 UTC by ayxos

This PR should fix the app always setting itself as the default protocol when it's not necessary to. On some operating systems (notably seen with linux) maybe rather has to do with snap in the referenced issue it closes it seems to always show a confirmation popup on every launch when the app is setting itself as a protocol client.

#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has *stopped working* or is *working incorrectly*, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉  https://github.com/sponsors/getferdi
  👉  https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.
- [ ] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

#### Motivation and Context

#### Screenshots

#### Checklist

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`npm run prepare-code`)
- [ ] `npm test` passes
- [ ] I tested/previewed my changes locally

#### Release Notes

2021-08-20 12:43 UTC, vraravam commented
@ayxos - please fill in the details in the description.

2021-08-20 12:44 UTC, vraravam commented on src/index.js
> +  if (!app.isDefaultProtocolClient(isDevMode ? 'ferdi-dev' : 'ferdi')) {
Isn't this wrong? I don't understand the logic of this change.

2021-08-20 12:46 UTC, vraravam requested changes
Please see question above.

2021-08-20 13:47 UTC, mhatvan commented on src/index.js
> +  if (!app.isDefaultProtocolClient(isDevMode ? 'ferdi-dev' : 'ferdi')) {
The code is correct, also see: https://github.com/ytmdesktop/ytmdesktop/pull/639/files 

It's just ugly due to the ternary, would also recommend to move it into a local variable and reuse it twice ;)

2021-08-20 14:38 UTC, vraravam commented
and btw: welcome and thanks for your contribution @ayxos !

2021-08-21 01:03 UTC, vraravam commented on src/index.js
> +  if (!app.isDefaultProtocolClient(isDevMode ? 'ferdi-dev' : 'ferdi')) {
I have done this change now.

2021-08-21 01:05 UTC, merged