Remove "stores.app.accentColor is marked as required" console error
getferdi/ferdi pull request #1859
Opened 2021-09-01 18:12 UTC by sad270

#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has *stopped working* or is *working incorrectly*, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉  https://github.com/sponsors/getferdi
  👉  https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.
- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
`AccentColor` is stored in `stores.settings.app.accentColor`, but we use `stores.app.accentColor` in the code and the linter has added `stores.app.accentColor` as required.
I didn't replace `stores.app.accentColor` by `stores.settings.app.accentColor` because it change default black background by purple (or accentColor) background on the loader screen (when you start Ferdi) this is not very beautiful.

#### Motivation and Context
Remove Console error and cleanup unused code
Fix: #1687

#### Checklist
- [X] My pull request is properly named
- [X] The changes respect the code style of the project (`npm run prepare-code`)
- [X] `npm test` passes
- [X] I tested/previewed my changes locally

2021-09-02 01:33 UTC, vraravam requested changes

2021-09-02 01:33 UTC, vraravam commented on src/components/ui/FullscreenLoader/index.js
> -          background: stores.app.accentColor,
@sad270 - I am not sure if *removing* the code is the correct fix. This will in fact remove the user-chosen skinning/style for this component. We need to figure out why, when this component is invoked/initialized, its being done so with the incorrect data-type.

2021-09-02 19:00 UTC, sad270 commented on src/components/ui/FullscreenLoader/index.js
> -          background: stores.app.accentColor,
I explain on the PR description.

Normally the fix should be replace `stores.app.accentColor` by `stores.settings.app.accentColor`and remove `stores.app.accentColor` from the `propTypes`

accentColor is stored in `stores.settings.app.accentColor` not in `stores.app.accentColor`.

I think using `stores.app.accentColor` is a mistake
And the linter see that  `stores.app.accentColor` is used but not added in propTypes so he add it in propTypes to fix linter issue instead of replace by correct variable.

But when you replace it by `stores.settings.app.accentColor` the loader is ugly. (White loader on purple background)
Currently, as `stores.app.accentColor` is not define, he doesn't set any background, so we have the default dark background on white loader. This is more beautiful.
IMO removing the bg color, made code cleanner and apparences cleanner too.

You can try if you want.
I'm on my phone, don't have computer until this weekend. I gonna add some screenshot this weekend to explain.

2021-09-02 22:40 UTC, vraravam commented on src/components/ui/FullscreenLoader/index.js
> -          background: stores.app.accentColor,
thanks for the explanation - i will checkout your branch and try it out later tonight when i get time. Thanks once again for the contribution.

2021-09-03 02:31 UTC, vraravam commented on src/components/ui/FullscreenLoader/index.js
> -          background: stores.app.accentColor,
yes - i see your point. Resolving this comment!

2021-09-03 02:34 UTC, merged