security: do not expose electron API to services 2
getferdi/ferdi pull request #1966
Opened 2021-09-18 23:30 UTC by kris7t

After refactoring some recipes in https://github.com/getferdi/ferdi/pull/1964, we no longer need to expose some APIs to recipes.

2021-09-19 03:51 UTC, vraravam requested changes
Do we want to include the `recipes` submodule changes in this PR?

2021-09-19 03:51 UTC, vraravam commented on CHANGELOG.md
> +- Improved context isolation for sandboxing services (#1964) (#1966) 💖 @kris7t
Sorry @kris7t - since the previous changes were released in the nightly.7, please create a new entry for the next nightly

2021-09-19 03:51 UTC, vraravam commented on src/webview/recipe.js
> -  releaseServiceWorkers: () => sessionHandler.releaseServiceWorkers(),
This is being invoked from `android-messages`, `devRant`, `lastpass`, `msteams`, `whatsapp` recipes.

2021-09-19 03:53 UTC, vraravam commented
Do we want to refer to the new changes from the `recipes` submodule here? They have already been merged into the `develop` branch as part of the nightly build and publish CI process.

2021-09-19 10:22 UTC, kris7t commented on src/webview/recipe.js
> -  releaseServiceWorkers: () => sessionHandler.releaseServiceWorkers(),
no, it's being invoked from `Ferdi`, not `window.ferdi`

2021-09-19 23:56 UTC, vraravam requested changes

2021-09-19 23:56 UTC, vraravam commented on src/webview/recipe.js
>    safeParseInt: text => badgeHandler.safeParseInt(text),
Can we remove this `setBadge` and `safeParseInt` as well? Seem to be redundant

2021-09-20 08:55 UTC, kris7t commented on src/webview/recipe.js
>    safeParseInt: text => badgeHandler.safeParseInt(text),
No, at least the `googlecalendar` recipe needs those in `webview-unsafe.js`

2021-09-20 09:18 UTC, vraravam commented on src/webview/recipe.js
>    safeParseInt: text => badgeHandler.safeParseInt(text),
ok - that's cool. tx

2021-09-20 20:47 UTC, kris7t commented
This was already done in #1968

2021-09-20 20:47 UTC, closed without merging

2021-09-20 23:23 UTC, vraravam commented on src/webview/lib/RecipeWebview.js
> -  // TODO Remove this once we implement a proper wrapper.
@kris7t - the changes to this file were NOT done in #1968 . Do you want to resurrect this PR and merge them?