feat: add a globalShortcut to toggle main window
getferdi/ferdi pull request #2002
Opened 2021-09-30 17:40 UTC by michaelhays

Fixes #1663

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Add an alt-x [global shortcut](https://www.electronjs.org/docs/latest/api/global-shortcut/) to toggle the main window

#### Motivation and Context
See #1663

#### Checklist
- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Add an alt-x global shortcut to toggle the main window

2021-09-30 17:42 UTC, michaelhays commented
Let me know if alt-x works for this, or if it would be better to use another shortcut.

Ideally, we'd let the user define the shortcut, but that would depend on #301 being implemented.

2021-09-30 23:32 UTC, vraravam requested changes

2021-09-30 23:32 UTC, vraravam commented on src/index.js
> +    globalShortcut.register('Alt+X', () => {
Please use the shortcut key constant defined in the `environment.ts` file. Please see other usages of the same to pass in the correct parameter.

2021-09-30 23:32 UTC, vraravam commented on src/index.js
> +  app.whenReady().then(() => {
Is this supposed to be active only for certain OS? Or is it applicable for all linux, macos and windows?

2021-10-01 06:52 UTC, mhatvan commented on src/index.js
> +  app.whenReady().then(() => {
Should work for all OS imo, tested it on Ubuntu, works as expected.

2021-10-01 06:55 UTC, vraravam commented on src/index.js
> +  app.whenReady().then(() => {
ok - let me resolve this comment

2021-10-03 03:17 UTC, vraravam commented on src/index.js
> +    globalShortcut.register('Alt+X', () => {
fixed in new commit

2021-10-03 03:21 UTC, vraravam approved these changes

2021-10-03 03:22 UTC, merged

2021-10-03 16:30 UTC, michaelhays commented on src/index.js
> +    globalShortcut.register('Alt+X', () => {
Thanks @vraravam!

2021-10-07 02:34 UTC, vraravam commented
@ylluminarious - I agree, this should have an option to be turned off. Let me work on it today/tomorrow.

2021-10-07 02:36 UTC, ylluminarious commented
@vraravam Thank you, I'll look forward to this in the next nightly release hopefully 🙇

2021-10-07 03:15 UTC, vraravam commented
For the immediate need, @ylluminarious - please drop back to the nightly before 25.

@michaelhays - configuring the shortcut can be done if this is exposed in the settings view. Lets take it 1 step at a time: lets first alleviate @ylluminarious 's pain by giving the ability to toggle it on/off. Then we can implement the exposure of the key binding

2021-10-07 03:37 UTC, vraravam commented
I just raised a PR (awaiting review) for the preference setting to toggle this on/off. Once it gets merged (or using a stacked PR), please go ahead and implement the user-chosen keyboard shortcut for this feature.

2021-10-08 04:13 UTC, ylluminarious commented
> For the immediate need, @ylluminarious - please drop back to the nightly before 25.

@vraravam Thanks for the advice. I tried downgrading to [`5.6.3-beta.1`,](https://github.com/getferdi/ferdi/releases/tag/v5.6.3-beta.1) but apparently that wasn't old enough. I had to go all the way back to [`5.6.3-nightly.19`.](https://github.com/getferdi/ferdi/releases/tag/v5.6.3-nightly.19)