shortcuts for toggling service
getferdi/ferdi pull request #2148
Opened 2021-10-27 06:32 UTC by Dee-Bajaj

**Description of Change**
Added shortcuts for toggling the service features
Disable notifications
Disable audio
Disable dark mode
Disable service

**Motivation and Context**
#1636 

**Screenshots**
<img width="203" alt="Screenshot 2021-10-30 at 11 57 58 PM" src="https://user-images.githubusercontent.com/66486870/139555195-165af4e0-436b-4e0c-b961-6e10daae02aa.png">

Dark mode enabled with shortcut :
<img width="1163" alt="Screenshot 2021-10-30 at 11 59 01 PM" src="https://user-images.githubusercontent.com/66486870/139555223-39b85ebc-73cb-4774-b4f8-62166ee1d01b.png">

Service Disabled with shortcut
<img width="1235" alt="Screenshot 2021-10-30 at 11 59 20 PM" src="https://user-images.githubusercontent.com/66486870/139555238-16adab7b-6a61-42bb-808e-846f1dcc6073.png">

 **Checklist**

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (npm run prepare-code)
- [x] npm test passes
- [x]  I tested/previewed my changes locally

2021-10-30 19:00 UTC, Dee-Bajaj commented on src/components/services/tabs/TabItem.js
> +        accelerator: `${cmdOrCtrlShortcutKey()}+N`,
@vraravam I have tried to incorporate changes in code and PR description. Please see if this can be accepted now.

2021-10-30 22:07 UTC, vraravam requested changes

2021-10-30 22:07 UTC, vraravam commented on src/environment.ts
> +export const toggleServiceFeaturesShortcutKey = (isAccelerator = true) =>
Since this `toggleServiceFeaturesShortcutKey` is only used in the single file `TabItem.js`, my recommendation would be for this to be moved into that file. Unless there's a known need for such duplication of utility messages across other files, we don't want to burden the `environment.ts`.

2021-10-30 22:07 UTC, vraravam commented on src/components/services/tabs/TabItem.js
> +        accelerator: `${toggleServiceFeaturesShortcutKey()}+N`,
`Cmd+Shift+N` is already taken to add a new workspace.

2021-10-31 06:10 UTC, Dee-Bajaj commented on src/environment.ts
> +export const toggleServiceFeaturesShortcutKey = (isAccelerator = true) =>
toggleServiceFeaturesShortcutKey has been removed from environment.ts and shortcuts locally created in TabItem.js

2021-10-31 06:11 UTC, Dee-Bajaj commented on src/components/services/tabs/TabItem.js
> +        accelerator: `${toggleServiceFeaturesShortcutKey()}+N`,
<img width="202" alt="Screenshot 2021-10-31 at 11 23 36 AM" src="https://user-images.githubusercontent.com/66486870/139570480-42b1afb2-4996-4e34-9a7b-455d67551292.png">

Hi,These are the updated combinations. I believe they are not being used already.

2021-10-31 07:22 UTC, vraravam approved these changes

2021-10-31 07:24 UTC, vraravam commented
@all-contributors - please add @Dee-Bajaj for code

2021-10-31 08:13 UTC, vraravam commented
@all-contributors - please add @DarsiSreelekha for code

2021-10-31 08:16 UTC, merged