Adjust number of columns for Split Mode
getferdi/ferdi pull request #2208
Opened 2021-11-10 13:27 UTC by niutech

This PR adds the _Number of columns_ input for the Split Mode, ranging from 1 to 5. The default value is 3 columns. This should fix #2108.

2021-11-10 15:56 UTC, vraravam requested changes

2021-11-10 15:56 UTC, vraravam commented on src/components/settings/settings/EditSettingsForm.js
> +                    placeholder="Number of columns"
Please use the `intl` package to conform to i18n.

2021-11-10 15:56 UTC, vraravam commented on src/stores/UIStore.ts
> +    return (
I assume this was put by the original committer to handle `undefined` and/or `null` values.

2021-11-10 19:44 UTC, vraravam commented on src/features/workspaces/store.js
> +    }, 500);
What are these changes?

2021-11-10 19:44 UTC, vraravam commented on src/features/workspaces/store.js
> +    }, 500);
Same here

2021-11-10 19:45 UTC, vraravam commented on src/components/settings/settings/EditSettingsForm.js
> +                    min="1"
Maybe these values can be moved to the `src/config.ts` file with meaningful names?

2021-11-11 06:45 UTC, niutech commented on src/features/workspaces/store.js
> +    }, 500);
I checked that we don't need to wait the whole second for Ferdi to swap the workspaces, so that Split Mode could hide some web services. Half a second should be enough.

2021-11-11 08:34 UTC, vraravam commented on src/components/settings/settings/EditSettingsForm.js
> +                    min="1"
Please fix this before I approve the PR

2021-11-12 10:51 UTC, niutech commented on src/components/settings/settings/EditSettingsForm.js
> +                    min="1"
Fixed.

2021-11-12 10:58 UTC, vraravam requested changes

2021-11-12 10:58 UTC, vraravam commented on src/config.ts
> +  minSplitColumns: 1,
This struct is mainly present for use in seeding the settings file upon installation. The `minSplitColumns` and `maxSplitColumns` should NOT come inside of this struct.

2021-11-12 22:47 UTC, vraravam commented on src/config.ts
> +  minSplitColumns: 1,
Done in the latest commit

2021-11-12 22:48 UTC, vraravam approved these changes

2021-11-12 22:52 UTC, merged